const cardPool = [
    { label: 'coin', image: '/Card/Front/itemIcons/Icons_01.png', bonus: 100 },
    { label: 'barrel', image: '/Card/Front/itemIcons/Icons_02.png', bonus: 80 },
    { label: 'plank', image: '/Card/Front/itemIcons/Icons_03.png', bonus: 60 },
    { label: 'door', image: '/Card/Front/itemIcons/Icons_04.png', bonus: 70 },
    { label: 'gemstone', image: '/Card/Front/itemIcons/Icons_05.png', bonus: 150 },
    { label: 'ruby', image: '/Card/Front/itemIcons/Icons_06.png', bonus: 500 },
    { label: 'crystal', image: '/Card/Front/itemIcons/Icons_07.png', bonus: 450 },
    { label: 'bookshelf', image: '/Card/Front/itemIcons/Icons_08.png', bonus: 120 },
    { label: 'grape', image: '/Card/Front/itemIcons/Icons_09.png', bonus: 125 },
    { label: 'dagger', image: '/Card/Front/itemIcons/Icons_10.png', bonus: 130 },
    { label: 'blue-gem', image: '/Card/Front/itemIcons/Icons_11.png', bonus: 200 },
    { label: 'sun', image: '/Card/Front/itemIcons/Icons_12.png', bonus: 170 },
    { label: 'jar', image: '/Card/Front/itemIcons/Icons_13.png', bonus: 110 },
    { label: 'chest', image: '/Card/Front/itemIcons/Icons_14.png', bonus: 250 },
    { label: 'wolf', image: '/Card/Front/itemIcons/Icons_15.png', bonus: 160 },
    { label: 'orb', image: '/Card/Front/itemIcons/Icons_16.png', bonus: 300 },
    { label: 'gemheart', image: '/Card/Front/itemIcons/Icons_17.png', bonus: 350 },
    { label: 'claw', image: '/Card/Front/itemIcons/Icons_18.png', bonus: 90 },
    { label: 'leaf', image: '/Card/Front/itemIcons/Icons_19.png', bonus: 60 },
    { label: 'feather', image: '/Card/Front/itemIcons/Icons_20.png', bonus: 50 },
    { label: 'spider', image: '/Card/Front/itemIcons/Icons_21.png', bonus: 140 },
    { label: 'redgem', image: '/Card/Front/itemIcons/Icons_22.png', bonus: 400 },
    { label: 'gloworb', image: '/Card/Front/itemIcons/Icons_23.png', bonus: 380 },
    { label: 'ruby-2', image: '/Card/Front/itemIcons/Icons_24.png', bonus: 500 },
    { label: 'rope', image: '/Card/Front/itemIcons/Icons_25.png', bonus: 50 },
    { label: 'shard', image: '/Card/Front/itemIcons/Icons_26.png', bonus: 180 },
    { label: 'leafscroll', image: '/Card/Front/itemIcons/Icons_27.png', bonus: 90 },
    { label: 'fang', image: '/Card/Front/itemIcons/Icons_28.png', bonus: 100 },
    { label: 'map', image: '/Card/Front/itemIcons/Icons_29.png', bonus: 200 },
    { label: 'woodblock', image: '/Card/Front/itemIcons/Icons_30.png', bonus: 70 },
    { label: 'web', image: '/Card/Front/itemIcons/Icons_31.png', bonus: 95 },
    { label: 'wool', image: '/Card/Front/itemIcons/Icons_32.png', bonus: 75 },
    { label: 'web-2', image: '/Card/Front/itemIcons/Icons_33.png', bonus: 85 },
    { label: 'drum', image: '/Card/Front/itemIcons/Icons_34.png', bonus: 100 },
    { label: 'compass', image: '/Card/Front/itemIcons/Icons_35.png', bonus: 120 },
    { label: 'container', image: '/Card/Front/itemIcons/Icons_36.png', bonus: 110 },
    { label: 'axe', image: '/Card/Front/itemIcons/Icons_37.png', bonus: 160 },
    { label: 'lamp', image: '/Card/Front/itemIcons/Icons_38.png', bonus: 130 },
    { label: 'barrel-2', image: '/Card/Front/itemIcons/Icons_39.png', bonus: 100 },
    { label: 'shard-white', image: '/Card/Front/itemIcons/Icons_40.png', bonus: 140 },
];

export default cardPool;
